### ISSUE TITLE
Feature: Always show note when creating/updating Timer

### ISSUE THREAD

**Issue by ursbraem** [andrejilderda/alfred-harvest#15]
Hey! I'm a bit late to the party, but just discovered that Workflow. Flawless, thanks!

What would it take to make `hvnt` always show up after manipulating (start / stop / adjust) an entry? 
Maybe I could add that myself and make a PR, but where to look?

**Comment by ajilderda** [comment]
Hi @ursbraem, you're welcome! To make Alfred open the note dialog after creating a new task you need to create two nodes:
![open-note-after-new-task](https://user-images.githubusercontent.com/487182/143567236-b6365131-36f7-4618-808f-a84720a6aa15.png)

In this case you still need to select the newly created task, but you don't have to `hvnt` anymore. 

Ideally you want to have the new task selected directly, but that requires the external `note`-node to be attached to either 'Replace note' or 'Add note' and passing the required arguments. If you decide to open a PR for this, please make this configurable.

**Comment by bdimaggio** [comment]
Hey @andrejilderda — just wanted to thank you for this advice. It worked perfectly on my setup! I will try to clear time to submit a PR as you suggest.

**Comment by andrejilderda** [comment]
@bdimaggio Great! Looking forward to seeing your PR.
