### ISSUE TITLE
Notes should break

### ISSUE THREAD

**Issue by aubreypwd** [andrejilderda/alfred-harvest#16]
Example:

I enter the note "Fixed this thing on this task.", when I want to append to that note, e.g. "Also went in a fixed another thing." My note reads:

```
Fixed this thing on this task.Also went in a fixed another thing.
```

![image](https://user-images.githubusercontent.com/1753298/145269032-43b85da0-c33e-4f7a-a24f-e5c49b002c53.png)

I think subsequent notes should break:

```
Fixed this thing on this task.
Also went in a fixed another thing.
```

![image](https://user-images.githubusercontent.com/1753298/145269108-e59ebc25-501d-4f2d-9a25-466c8ba1c60a.png)

...or maybe even double-break. For now I will have to add a space and a separator: `\s- Also went in a fixed another thing.`

---

This is great (replaced an old version I built that stopped working)! 💟

**Comment by ajilderda** [comment]
Hi @aubreypwd , I actually use a slightly modified `update-task.js` that adds a break before every en-dash (which you can add by pressing <kbd>alt</kbd>+<kbd>-</kbd>), so that you end up with: 
<img width="827" alt="image" src="https://user-images.githubusercontent.com/487182/145271934-e1b54813-a2c5-4e57-afea-2fa6d04c8796.png">

I've just added it to releases: 
https://github.com/ajilderda/alfred-harvest/releases/tag/1.1.4

Let me know if that works for you!

**Comment by aubreypwd** [comment]
1. I didn't know `alt + -` resulted in an en-dash `–` so thanks for that! 
2. It worked!

![image](https://user-images.githubusercontent.com/1753298/145275200-8a0ac3ba-4563-49b5-b999-1f1d61920fe7.png)

Personally, I would prefer if it did this for every entry that started with normal `^\s-` (no `alt`), but I'm not complaining! This works, just would be a few less keystrokes IMHO if we could do that.

**Comment by ajilderda** [comment]
I went for an en-dash because I can do a simple `replace`. For regular dashes this would pose problems, because a word-with-dashes would result in:

- word
- with
- dashes

Of course this is solvable, but I like en-dashes typographically. 😉

**Comment by ajilderda** [comment]
Btw. you can always right-click the workflow in the Alfred preferences › Open in Finder and open `src/update-task.js` and change the en-dash to a regular dash!

**Comment by aubreypwd** [comment]
Maybe I can try taking a look sometime, as I wonder what can be done with REGEX, e.g. `^\s-`, if I get time I might submit a PR because I understand the problem!
