### ISSUE TITLE
Add manual tracking option to new tasks.

### ISSUE THREAD

**Issue by oikmar** [andrejilderda/alfred-harvest#21]
Thank you for the work flow integration. Eases day-to-day tracking 👏🏽 .

There is one scenario i am missing though, which i am unsure whether is supported in the current implementation. The ability to assign a duration to a new task, without having to start/stop a new timer for that task. Essentially, that would be to log hours to a new task from the workflow.

Is that something possible to in this workflow?

**Comment by andrejilderda** [comment]
Hi @oikmar, no unfortunately that is currently not possible. At the moment I don't have time to add this feature, but I'd be happy to look at a PR though. 😊
