### ISSUE TITLE
Unable to complete initial setup, no prompt for account number is shown

### ISSUE THREAD

**Issue by ahathaway** [andrejilderda/alfred-harvest#24]
Hello, thank you for making this wonderful tool!

I am unfortunately unable to get it setup correctly and am wondering if I am missing something?

1. I type `hvs` into my Alfred prompt and hit enter. 
2. It asks for my token, I paste it in and hit enter. 
3. Nothing happens after this step. 

From looking at the instructions, and the workflow itself, it seems like the next prompt should come up and ask for my account number. 

- So this leads me to wonder, is this compatible with Alfred 5.0.6? 
- Is this compatible with MacOS Monterey 12.6.3?
- Is this compatible with node v16.x?
- Is there anything else I should be looking for or at?

Thanks!

**Comment by andrejilderda** [comment]
Hi @ahathaway , your setup should definitely work. The API token is stored in Keychain and the first time you run the workflow you may be prompted to grant access to it. Maybe you accidentally declined it?

What I suggest you to do is to open 'Keychain Access' and search for `com.andrejilderda.harvest`, right-click, delete the item and retry the [setup steps as described here](https://github.com/andrejilderda/alfred-harvest#installation--setup). Let me know if it works!

**Comment by andrejilderda** [comment]
@ahathaway If the previous solution didn't work for you you may want to check out the [latest version](https://github.com/andrejilderda/alfred-harvest/releases/tag/2.0.0) which should work with newer versions of node and uses Alfred's config for setting the account id. Closing this but feel free to reopen.
